monitor=,1920x1080@240,auto,auto

input {
    kb_layout = us,ge
    kb_options = grp:menu_toggle
}

source = ./env.conf
source = ./binds.conf
source = ./animations.conf
source = ./window.conf
source = ./exec.conf