# Alacritty Configuration (TOML format)

[window]
opacity = 0.9

[scrolling]
history = 10000

[font]
size = 12.0
offset = { x = -1, y = 0 }
glyph_offset = { x = 0, y = 0 }

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[colors.primary]
background = "#1e1e1e"
foreground = "#d4d4d4"

[colors.selection]
text = "#1e1e1e"
background = "#d4d4d4"

[cursor]
style = "Beam"
unfocused_hollow = false

[terminal.shell]
program = "/bin/bash"
